In [1]:
import numpy as np
from numpy import genfromtxt

In [2]:
data = genfromtxt("DATA/bank_note_data.txt",delimiter=',')

In [3]:
data

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699,   0.     ],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ,   0.     ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645,   0.     ],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ,   1.     ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ,   1.     ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ,   1.     ]])

In [4]:
labels = data[:,4]

In [5]:
labels

array([0., 0., 0., ..., 1., 1., 1.])

In [6]:
features = data[:,0:4]

In [7]:
features

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ]])

In [8]:
X = features
y = labels

In [9]:
from sklearn.model_selection import train_test_split

In [10]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [12]:
len(X_train)

919

In [13]:
len(X_test)

453

In [14]:
from sklearn.preprocessing import MinMaxScaler

In [17]:
scaler_object = MinMaxScaler()

In [18]:
scaler_object.fit(X_train)

MinMaxScaler()

In [19]:
scaled_X_train = scaler_object.transform(X_train)

In [20]:
scaled_X_test = scaler_object.transform(X_test)

In [21]:
scaled_X_train.max()

1.0000000000000002

In [23]:
scaled_X_test

array([[0.62098955, 0.75284662, 0.21900753, 0.5730998 ],
       [0.48778602, 0.82175665, 0.09174727, 0.56211079],
       [0.51158363, 0.77924916, 0.13830875, 0.50392598],
       ...,
       [0.76115065, 0.62415668, 0.27251204, 0.83616757],
       [0.9047516 , 0.90329171, 0.03658247, 0.42267079],
       [0.49296526, 0.86039507, 0.06714046, 0.1622583 ]])

In [38]:
from keras.models import Sequential
from keras.layers import Dense

In [39]:
model = Sequential()

model.add(Dense(4,input_dim=4,activation='relu'))

model.add(Dense(8,activation='relu'))

model.add(Dense(1,activation='sigmoid'))

In [40]:
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=["accuracy"])

In [41]:
model.fit(scaled_X_train,y_train,epochs=50,verbose=2)

Epoch 1/50
29/29 - 1s - loss: 0.6321 - accuracy: 0.5528
Epoch 2/50
29/29 - 0s - loss: 0.6170 - accuracy: 0.5974
Epoch 3/50
29/29 - 0s - loss: 0.6041 - accuracy: 0.6627
Epoch 4/50
29/29 - 0s - loss: 0.5912 - accuracy: 0.6746
Epoch 5/50
29/29 - 0s - loss: 0.5783 - accuracy: 0.6975
Epoch 6/50
29/29 - 0s - loss: 0.5648 - accuracy: 0.7171
Epoch 7/50
29/29 - 0s - loss: 0.5513 - accuracy: 0.7508
Epoch 8/50
29/29 - 0s - loss: 0.5364 - accuracy: 0.7617
Epoch 9/50
29/29 - 0s - loss: 0.5211 - accuracy: 0.7791
Epoch 10/50
29/29 - 0s - loss: 0.5060 - accuracy: 0.7911
Epoch 11/50
29/29 - 0s - loss: 0.4902 - accuracy: 0.8205
Epoch 12/50
29/29 - 0s - loss: 0.4733 - accuracy: 0.8183
Epoch 13/50
29/29 - 0s - loss: 0.4565 - accuracy: 0.8433
Epoch 14/50
29/29 - 0s - loss: 0.4390 - accuracy: 0.8629
Epoch 15/50
29/29 - 0s - loss: 0.4214 - accuracy: 0.8738
Epoch 16/50
29/29 - 0s - loss: 0.4039 - accuracy: 0.8825
Epoch 17/50
29/29 - 0s - loss: 0.3856 - accuracy: 0.9086
Epoch 18/50
29/29 - 0s - loss: 0.3672 - 

In [43]:
#model.predict_classes(scaled_X_test)

In [46]:
model.metrics_names

['loss', 'accuracy']

from 

In [47]:
from sklearn.metrics import confusion_matrix,classification_report

In [48]:
predictions = model.predict_classes(scaled_X_test)

d:\study\envs\python_cv\lib\site-packages\tensorflow\python\keras\engine\sequential.py:450: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


In [49]:
confusion_matrix(y_test,predictions)

array([[254,   3],
       [  5, 191]], dtype=int64)

In [50]:
print(classification_report(y_test,predictions))

              precision    recall  f1-score   support

         0.0       0.98      0.99      0.98       257
         1.0       0.98      0.97      0.98       196

    accuracy                           0.98       453
   macro avg       0.98      0.98      0.98       453
weighted avg       0.98      0.98      0.98       453



In [51]:
model.save('mysupermodel.h5')

In [52]:
from keras.models import load_model

In [53]:
newmodel = load_model('mysupermodel.h5')

In [54]:
newmodel.predict_classes(scaled_X_test)

d:\study\envs\python_cv\lib\site-packages\tensorflow\python\keras\engine\sequential.py:450: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


array([[0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
    