In [16]:
import cv2
import numpy as np

In [11]:
img = cv2.imread('DATA/crossword.jpg',0)

In [29]:
print(img)

[[218 219 222 ... 216 217 216]
 [223 220 224 ... 212 214 214]
 [224 225 224 ... 209 210 210]
 ...
 [226 224 222 ... 220 224 223]
 [217 220 226 ... 223 221 223]
 [211 213 219 ... 224 225 220]]


In [14]:
vector = img.reshape(0,1)

ValueError: cannot reshape array of size 446348 into shape (0,1)

In [26]:
vector = np.asarray(img).reshape(-1)

In [27]:
print(vector.shape)

(446348,)


In [2]:
fruits = ['orange','apple','pear','banana','kiwi','apple','banana']
fruits.count('apple')

2

In [3]:
fruits.count('tangerine')

0

In [4]:
fruits.index('banana')

3

In [5]:
fruits.index('banana',4)

6

In [6]:
fruits

['orange', 'apple', 'pear', 'banana', 'kiwi', 'apple', 'banana']

In [7]:
fruits.sort()

In [8]:
fruits

['apple', 'apple', 'banana', 'banana', 'kiwi', 'orange', 'pear']

In [9]:
fruits.pop()

'pear'

In [21]:
squares = []

In [18]:
for x in range(10):
    squares.append(x**2)

In [19]:
squares

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [23]:
squares = list(map(lambda x: x**2, range(10)))

In [24]:
squares

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [27]:
squares = [x**2 for x in range(10)]

In [28]:
squares

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [29]:
[(x,y) for x in [1,2,3] for y in [3,1,4] if x!=y]

[(1, 3), (1, 4), (2, 3), (2, 1), (2, 4), (3, 1), (3, 4)]

In [33]:
combs = []
for x in range(0,3):
 for y in [3,2,4]:
    if x!=y:
        combs.append([x,y])
combs

[[0, 3], [0, 2], [0, 4], [1, 3], [1, 2], [1, 4], [2, 3], [2, 4]]

In [37]:
def get_comb(x,y,z):
    return [[i,j,k] for i in range(0,x+1) for j in range(0,y+1) for k in range(0,z+1) if x!=y!=z]
    

In [39]:
get_comb(1,1,1)

[]